### ISSUE TITLE
Otherwise

### ISSUE THREAD

**Issue by josibuttazzoni** [MartinSchvartz/TpsIndividuales#6]
https://github.com/MartinSchvartz/TpsIndividuales/blob/b9566047bb902e80ff4a8b383ff77ed77c46885c/TpMonopoly/src/Lib.hs#L91

Aca la segunda condicion no hace falta, porque si no entra al primer caso, si o si va a entrar en el segundo (no importa el empate)

**Comment by MartinSchvartz** [comment]
Como que no? Si a mi me decis que perdi y tenemos la misma cantidad de plata rompo todo xd

**Comment by josibuttazzoni** [comment]
Obvio que yo tambien, por eso no empato y gano

**Comment by MartinSchvartz** [comment]
jajajjajajajaajaj gran respuesta
